name: Build and Deploy HonKit Book

on:
  push:
    branches: [ ukrainian-translation, main ]
  pull_request:
    branches: [ ukrainian-translation ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.18.1'

    - name: Install HonKit
      run: |
        npm install honkit --save-dev
        npx honkit --version

    - name: Build HonKit book
      run: |
        npm run build

    - name: Deploy into main site
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAT }}
        external_repository: elleoma/elleoma.github.io
        publish_dir: ./_book
        destination_dir: reversing
        publish_branch: ukrainian-translation
